Add task to enable netconf
ansible-network/cisco_iosxr pull request #2
Opened 2018-08-13 10:38 UTC by ganeshrn

Add task to enable netconf

2018-08-13 13:04 UTC, privateip requested changes

2018-08-13 13:04 UTC, privateip commented on defaults/main.yml
> +netconf_port: 830
vars should be prefixed with `iosxr_`.  You can provide vanity vars as such:

`iosxr_netconf_port: "{{ netconf_port | default(830) }}`

2018-08-13 17:05 UTC, ganeshrn commented on defaults/main.yml
> +netconf_port: 830
Fixed

2018-08-13 17:06 UTC, ganeshrn commented
ready_for_review

2018-08-28 08:33 UTC, justjais approved these changes

2018-08-31 12:12 UTC, privateip approved these changes

2018-08-31 12:12 UTC, merged